// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "API для изучения иностранных слов. Позволяет создавать, управлять и практиковать переводы слов и фраз.",
        "title": "API Изучение иностранного языка",
        "contact": {
            "name": "API поддержка",
            "email": "nanomalkin@gmail.com"
        },
        "version": "1.123"
    },
    "host": "localhost:8080",
    "basePath": "/api",
    "tags": [
        {
            "name": "auth",
            "description": "Аутентификация пользователей"
        },
        {
            "name": "translations",
            "description": "Управление переводами и изучением слов"
        }
    ],
    "paths": {
        "/auth/sign-up": {
            "post": {
                "tags": ["auth"],
                "summary": "Регистрация нового пользователя",
                "description": "Создание нового аккаунта для изучения переводов",
                "parameters": [{
                    "in": "body",
                    "name": "input",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/User"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "example": "507f1f77bcf86cd799439011"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "tags": ["auth"],
                "summary": "Авторизация пользователя",
                "description": "Получение токена для доступа к API",
                "parameters": [{
                    "in": "body",
                    "name": "input",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/SignInInput"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string",
                                    "example": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                                }
                            }
                        }
                    }
                }
            }
        },
        "/translations": {
            "get": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Получить все переводы пользователя",
                "description": "Возвращает список всех слов и фраз для изучения",
                "parameters": [
                    {
                        "name": "limit",
                        "in": "query",
                        "description": "Максимальное количество возвращаемых переводов",
                        "required": false,
                        "type": "integer"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/Translation"
                                    }
                                },
                                "total": {
                                    "type": "integer",
                                    "example": 123
                                },
                                "source": {
                                    "type": "string",
                                    "example": "cache",
                                    "description": "Источник данных: cache или db"
                                },
                                "duration_ms": {
                                    "type": "integer",
                                    "example": 12,
                                    "description": "Время обработки запроса в миллисекундах"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Добавить новое слово/фразу для изучения",
                "parameters": [{
                    "in": "body",
                    "name": "input",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/TranslationInput"
                    }
                }],
                "responses": {
                    "200": {
                        "description": "Успешное создание",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "string",
                                    "example": "507f1f77bcf86cd799439011"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/translations/{id}": {
            "get": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Получить конкретный перевод",
                "parameters": [{
                    "in": "path",
                    "name": "id",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Translation"
                        }
                    }
                }
            },
            "put": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Проверить перевод",
                "description": "Отправка перевода для проверки правильности",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "in": "body",
                        "name": "input",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CheckTranslationInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная проверка",
                        "schema": {
                            "$ref": "#/definitions/CheckResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Удалить слово/фразу из изучаемых",
                "parameters": [{
                    "in": "path",
                    "name": "id",
                    "required": true,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "Успешное удаление",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "ok"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/translations/post100": {
            "post": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Создать тестовый набор из 100 переводов",
                "description": "Создает 100 тестовых переводов на основе базового набора из 10 слов",
                "parameters": [{
                    "in": "query",
                    "name": "forAllUsers",
                    "required": false,
                    "type": "boolean",
                    "description": "Создать тестовые данные для всех пользователей"
                }],
                "responses": {
                    "200": {
                        "description": "Успешное создание тестовых данных",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "ok"
                                },
                                "count": {
                                    "type": "integer",
                                    "example": 100
                                },
                                "ids": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    },
                                    "example": ["507f1f77bcf86cd799439011"]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/translations/post100k": {
            "post": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Создать тестовый набор из 100000 переводов",
                "description": "Создает 100000 тестовых переводов на основе базового набора из 10 слов",
                "parameters": [{
                    "in": "query",
                    "name": "forAllUsers",
                    "required": false,
                    "type": "boolean",
                    "description": "Создать тестовые данные для всех пользователей"
                }],
                "responses": {
                    "200": {
                        "description": "Успешное создание тестовых данных",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "ok"
                                },
                                "count": {
                                    "type": "integer",
                                    "example": 100000
                                },
                                "ids": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    },
                                    "example": ["507f1f77bcf86cd799439011"]
                                }
                            }
                        }
                    }
                }
            }
        },
        "/translations/delete_all": {
            "delete": {
                "security": [{"ApiKeyAuth": []}],
                "tags": ["translations"],
                "summary": "Удалить все переводы пользователя",
                "description": "Удаляет все переводы текущего пользователя",
                "responses": {
                    "200": {
                        "description": "Успешное удаление всех переводов",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string",
                                    "example": "ok"
                                },
                                "deleted_count": {
                                    "type": "integer",
                                    "example": 100
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "User": {
            "type": "object",
            "required": ["name", "username", "password"],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "username": {
                    "type": "string",
                    "example": "johndoe"
                },
                "password": {
                    "type": "string",
                    "example": "secretpassword"
                }
            }
        },
        "SignInInput": {
            "type": "object",
            "required": ["username", "password"],
            "properties": {
                "username": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "Translation": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "phrase": {
                    "type": "string",
                    "example": "Hello"
                },
                "expected_translation": {
                    "type": "string",
                    "example": "Привет"
                },
                "done": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "TranslationInput": {
            "type": "object",
            "required": ["phrase", "expected_translation"],
            "properties": {
                "phrase": {
                    "type": "string",
                    "example": "Hello"
                },
                "expected_translation": {
                    "type": "string",
                    "example": "Привет"
                }
            }
        },
        "CheckTranslationInput": {
            "type": "object",
            "required": ["translation"],
            "properties": {
                "translation": {
                    "type": "string",
                    "example": "Привет"
                }
            }
        },
        "CheckResponse": {
            "type": "object",
            "properties": {
                "correct": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Title:            "API обучения переводу",
	Description:      "API для изучения иностранных слов с системой перевода",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
